Rails:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  DisplayStyleGuide: true

  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Max: 100

# Metrics/MethodLength:
#   Max: 20

# Metrics/ClassLength:
#   Max: 200

# Metrics/CyclomaticComplexity:
#   Max: 10

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
